#!/usr/bin/env python
import sys
import subprocess
import os

filename = sys.argv[1]
with open(filename, 'rb') as f:
    lines = f.readlines()

name = subprocess.check_output(["git", "config", "user.name"]).rstrip()
email = subprocess.check_output(["git", "config", "user.email"]).rstrip()
lines.insert(1, b'# Author: ' + name + b' <' + email + b'>\n')

with open(filename, 'wb') as f:
    f.writelines(lines)
