#!/usr/bin/env python
import sys
import subprocess

filename = sys.argv[1]
source = sys.argv[2] if len(sys.argv) > 2 else None

with open(filename, 'rb') as f:
    lines = f.readlines()

# When 'git commit -m' or 'git commit -F',
# the commit command runs with --cleanup=whitespace, in other words,
# lines with leading '#' are not treated as comments.
# So do nothing with -m or -F option.
if source == 'message':
    sys.exit(0)

name = subprocess.check_output(["git", "config", "user.name"]).rstrip()
email = subprocess.check_output(["git", "config", "user.email"]).rstrip()
lines.insert(1, b'# Author: ' + name + b' <' + email + b'>\n')

with open(filename, 'wb') as f:
    f.writelines(lines)
